### ISSUE TITLE
Auto selecting test assembly does not work in x86 or mode

### ISSUE THREAD

**Issue by codereflection** [codereflection/Giles#11]
When you have Giles watching a solution that does not target the default bin\Debug output folder structure, Giles is unable to find the assembly to test, resulting in the following error:

``` text
System.IO.FileNotFoundException: Could not load file or assembly 'file:///C:\Dev\Personal\GilesTest\GilesTest\bin\Debug\GilesTest.dll' or one of its dependencies. The system cannot find the file specified.
File name: 'file:///C:\Dev\Personal\GilesTest\GilesTest\bin\Debug\GilesTest.dll'

Server stack trace:
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Giles.Core.AppDomains.GilesAppDomainRunner.Run(String testAssemblyPath)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Int32 methodPtr, Boolean fExecuteInContext, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg, Int32 methodPtr, Boolean fExecuteInContext)

Exception rethrown at [0]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Giles.Core.AppDomains.GilesAppDomainRunner.Run(String testAssemblyPath)
   at Giles.Core.AppDomains.GilesAppDomainManager.Run(String testAssemblyPath)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].



=======  TEST RUNNER RESULTS =======
Something went wrong, check the Giles console window for more details
```

**Comment by codereflection** [comment]
A workaround for this issue until it is resolves is to point Giles to the correct test assembly with the -t command line option.

**Comment by mpareja** [comment]
Can you post the sample project or at least the .csproj file?

**Comment by mpareja** [comment]
When determining the assembly filepath, I'm resolving the assembly file path using the default Configuration and Platform specified in the project file.  Are you trying to run the tests using a different config/platform than what is in the .csproj file?
