### ISSUE TITLE
Exception for solution which does not have AnyCPU platform

### ISSUE THREAD

**Issue by flcdrg** [codereflection/Giles#39]
Our solution does not have 'AnyCPU' platform, which Giles seems to assume will exist. Getting this exception:

```
Unhandled Exception: System.InvalidOperationException: No value found for property 'OutputPath' using platform configuration 'Debug|AnyCPU'
   at Giles.Core.Configuration.MsBuildProject.GetPropertyValue(String platformConfig, String property)
   at Giles.Core.Configuration.MsBuildProject.GetAssemblyFilePath(String projectFilePath)
   at Giles.Core.Configuration.TestAssemblyFinder.FindTestAssembliesIn(String solutionFilePath)
   at Giles.Program.FindTestAssembly(String solutionPath)
   at Giles.Program.GetTestAssemblies(CLOptions options)
   at Giles.Program.GetGilesConfigFor(CLOptions options)
   at Giles.Program.Main(String[] args)
```

**Comment by codereflection** [comment]
That's definitely a bug. Will look into it.

**Comment by flcdrg** [comment]
I've done some further investigation and discovered that this is caused by a test project that is setting the default Platform (in the .csproj file) to 'AnyCPU', but there are no PropertyGroup sections with 'AnyCPU' - so I guess this is really a problem with the .csproj file being inconsistent. I might submit a patch to improve the logging around this though.
