### ISSUE TITLE
Giles is not running well with NUnit Test Adapter for Visual Studio

### ISSUE THREAD

**Issue by Monomachus** [codereflection/Giles#50]
Exception that I am getting

System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.

Server stack trace:
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Giles.Core.Utility.AssemblyExtensions.GetRelevantTypes[T](Assembly assembly)
   at Giles.Core.Utility.AssemblyExtensions.FromAssemblyGetInstancesOfType[T](String file)
   at Giles.Core.Utility.TypeLoader.<>c__DisplayClass1`1.<GetNewInstancesByType>b__0(String file)
   at Giles.Core.Utility.RandomExtensionMethods.Each[T](IEnumerable`1 enumerable, Action`1 action)
   at Giles.Core.Utility.TypeLoader.GetNewInstancesByType[T]()
   at Giles.Core.Runners.TestFrameworkResolver..ctor()
   at Giles.Core.AppDomains.GilesAppDomainRunner.Run(String testAssemblyPath, List`1 filters)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server,
 Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Giles.Core.AppDomains.GilesAppDomainRunner.Run(String testAssemblyPath, List`1 filters)
   at Giles.Core.AppDomains.GilesAppDomainManager.Run(String testAssemblyPath, List`1 filters)
Test run completed in 0.117506 seconds

**Comment by codereflection** [comment]
What version of NUnit are you using? What is your target framework version?
